#!/usr/bin/bash

"""
make sure you have already install ros-melodic
if not, try to do that by following instructions from internet
"""


# run in your own catkin/src

# clone simulation and testing project

git clone https://github.com/MosHumanoid/humanoid_league_visualization.git
git clone https://github.com/MosHumanoid/humanoid_league_misc.git
git clone https://github.com/MosHumanoid/wolfgang_robot.git
git clone https://github.com/MosHumanoid/humanoid_base_footprint.git

# make your catkin，make sure you have installed catkin tools 

cd ../
catkin build

# source your code

cd devel
source setup.bash
